### ISSUE TITLE
Update TRAP to read climate change data files

### ISSUE THREAD

**Issue by ollis-nwcouncil** [NWCouncil/trap2#29]
You may have to do some work soon.  

We created a branch off the master called trap_CC.

John is working on it.  We will upload when he is done modifying.  You will be notified.

**Comment by ollis-nwcouncil** [comment]
This is what happens when you teach people how to use new programs...

**Comment by bkkujala** [comment]
I see a change in the code, but I don't see any updates to the input files.  Are they included in the master branch?

**Comment by ollis-nwcouncil** [comment]
The input files are uploaded, per what John F. sent me.

**Comment by bkkujala** [comment]
The problem seems to be related to writing the headers for the files, the program errors out before much is done.  This seems related to some old school fortran here:
https://github.com/NWCouncil/trap2/blob/f3c59cdde9cd81ef08e886a1a49f702307249f48/trap2.F90#L2078

More research needed but the problem seems to be File I/O not related to anything in the LP logic.

**Comment by bkkujala** [comment]
Upon further inspection, this could be a result of the very first system being infeasible.
![TRAP Infeas](https://user-images.githubusercontent.com/7729775/73413253-eec07b00-42bf-11ea-8057-a5c8133f330d.PNG)

**Comment by bkkujala** [comment]
Turns out the problem was many infeasible systems because reserves cannot be held on the PacifiCorp BA in the climate change data.  Setting reserves to zero for these data resolves the issue.  This is now fixed in the CC branch and would not be an issue in the master branch.  Closing this issue.
